# Generated by Django 3.0 on 2022-10-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancas', '0008_delete_banca_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('GREEN', 'Green'), ('RED', 'Red')], default='AGUARDANDO', max_length=194, verbose_name='status')),
                ('time_casa', models.CharField(blank=True, max_length=194, null=True, verbose_name='Time jogando em casa')),
                ('time_fora', models.CharField(blank=True, max_length=194, null=True, verbose_name='Time jogando fora')),
                ('valor_aposta', models.IntegerField(verbose_name='Valor apostado R$')),
                ('cotacao', models.FloatField(verbose_name='Cotação')),
                ('horario_aposta', models.DateTimeField(auto_now_add=True, verbose_name='Horario aposta')),
                ('banca_apostada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancas.Banca', verbose_name='Banca que aconteceu a aposta')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': ('Bilhetes',),
                'db_table': 'bilhete',
            },
        ),
    ]
