# Generated by Django 3.0 on 2022-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banca', models.CharField(max_length=80, verbose_name='Nome da Banca')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Saldo')),
                ('valor_da_entrada', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor da entrada')),
                ('valor_da_saida', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor da Saída')),
                ('data_registro_banca', models.DateTimeField(auto_now_add=True, verbose_name='Data inicio banca')),
            ],
            options={
                'verbose_name': ('Banca',),
                'verbose_name_plural': ('Bancas',),
                'db_table': 'banca',
            },
        ),
    ]
