# Generated by Django 3.0 on 2022-10-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0003_auto_20221010_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banca_entrada',
            options={},
        ),
        migrations.AlterModelTable(
            name='banca_entrada',
            table=None,
        ),
    ]
