# Generated by Django 3.0 on 2022-10-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0004_auto_20221010_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bancas_uma_pra_uma',
        ),
    ]
