# Generated by Django 3.0 on 2022-10-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0005_delete_bancas_uma_pra_uma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancas_uma_pra_uma',
            fields=[
                ('bancas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bancas.Banca')),
            ],
        ),
    ]
