# Generated by Django 3.0 on 2022-10-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0006_bancas_uma_pra_uma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banca_entrada',
            options={'verbose_name': ('Banca Entrada',), 'verbose_name_plural': ('Emtradas banca',)},
        ),
        migrations.AlterModelTable(
            name='banca_entrada',
            table='bancas_entrada',
        ),
        migrations.DeleteModel(
            name='Bancas_uma_pra_uma',
        ),
    ]
