# Generated by Django 3.0 on 2022-10-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancas', '0007_auto_20221010_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banca_entrada',
        ),
    ]
