# Generated by Django 3.0 on 2022-10-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancas', '0008_delete_banca_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Valor da entrada')),
                ('selecionar_banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancas.Banca', verbose_name='Selecione a banca')),
            ],
            options={
                'verbose_name': ('Banca Entrada',),
                'verbose_name_plural': ('Entradas bancas',),
                'db_table': 'banca_entrada',
            },
        ),
    ]
